
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obhewylgtyxuuhrmwzvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iaGV3eWxndHl4dXVocm13enZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDQ0NzYsImV4cCI6MjA2MjAyMDQ3Nn0.PmuKGuKKLHhBQLK2YVBYJqQOBkazjZOGzJ1Tks4p7hA";

// Create a single supabase client for interacting with your database
export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true
    },
    global: {
      headers: {
        'x-application-name': 'imovan-app',
      },
    },
    realtime: {
      timeout: 30000
    }
  }
);
